name: go_to_gym
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.8
  geolocator: ^14.0.1
  google_maps_flutter: ^2.12.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geocoding: ^4.0.0
  timeago: ^3.7.1
  google_generative_ai: ^0.4.7
  flutter_markdown: ^0.7.7+1
  firebase_remote_config: ^5.4.4
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  flutter_animate: ^4.5.0
  flutter_image_compress: ^2.4.0
  rxdart: ^0.28.0
  flutter_launcher_icons: ^0.14.4
  firebase_messaging: 15.2.6
  http: ^1.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  google_fonts: ^6.1.0
  animate_do: ^2.1.0
  smooth_page_indicator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
